export type StockType = "depot" | "watchlist";

export interface StockItem {
  id: string;
  name: string;
  sector: string;
  ticker: string;        // Anzeige / Hauptticker
  priceTicker?: string;  // optional eigener Ticker für Kursabfrage
  wkn: string;
  isin?: string;
  type: StockType;

  // Positionsdaten
  shares: number;
  buyPrice: number;
  currentPrice?: number;

  // Strategie
  targetWeight: number;   // Prozentgewichtung im Zieldepot
  buyZoneMin?: number;
  buyZoneMax?: number;
  stopBuy?: number;
  stopLoss?: number;

  // Meta
  status?: "Live" | "Watchlist";
  notes?: string;
}

export const STOCKS: StockItem[] = [
  {
    id: "nvda",
    name: "Nvidia",
    sector: "KI / GPU Infrastruktur",
    ticker: "NVDA",
    priceTicker: "NVDA",
    wkn: "918422",
    isin: "US67066G1040",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 30,
    buyZoneMin: 160,
    buyZoneMax: 170,
    stopBuy: 195,
    stopLoss: 145,
    status: "Live",
    notes: "Kernposition im Depot",
  },
  {
    id: "isrg",
    name: "Intuitive Surgical",
    sector: "Medizinrobotik",
    ticker: "ISRG",
    priceTicker: "ISRG",
    wkn: "888024",
    isin: "US46120E6023",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 20,
    buyZoneMin: 450,
    buyZoneMax: 470,
    stopBuy: 515,
    stopLoss: 420,
    status: "Live",
    notes: "Qualitätswert, eher defensiver als viele andere Robotik-Titel",
  },
  {
    id: "abb",
    name: "ABB",
    sector: "Industrieautomation",
    ticker: "ABB",
    priceTicker: "ABB",
    wkn: "675089",
    isin: "US0003752047",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 15,
    buyZoneMin: 75,
    buyZoneMax: 80,
    stopBuy: 92,
    stopLoss: 70,
    status: "Live",
    notes: "ADR-Variante passend zur aktuellen US-Kurslogik",
  },
  {
    id: "sym",
    name: "Symbotic",
    sector: "Logistikrobotik",
    ticker: "SYM",
    priceTicker: "SYM",
    wkn: "A3DK1X",
    isin: "US87151X1019",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 10,
    buyZoneMin: 42,
    buyZoneMax: 46,
    stopBuy: 55,
    stopLoss: 38,
    status: "Live",
    notes: "Wachstumswert, deutlich volatiler",
  },
  {
    id: "ter",
    name: "Teradyne",
    sector: "Cobots / Testsysteme",
    ticker: "TER",
    priceTicker: "TER",
    wkn: "859892",
    isin: "US8807701029",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 15,
    buyZoneMin: 260,
    buyZoneMax: 275,
    stopBuy: 315,
    stopLoss: 240,
    status: "Live",
    notes: "Robotik + Testsysteme",
  },
  {
    id: "path",
    name: "UiPath",
    sector: "Software-Robotik / RPA",
    ticker: "PATH",
    priceTicker: "PATH",
    wkn: "A3CND6",
    isin: "US90364P1057",
    type: "depot",
    shares: 0,
    buyPrice: 0,
    targetWeight: 10,
    buyZoneMin: 9,
    buyZoneMax: 10.5,
    stopBuy: 13,
    stopLoss: 8,
    status: "Live",
    notes: "Spekulativer als die Kernwerte",
  },

  // WATCHLIST
  {
    id: "tsla",
    name: "Tesla",
    sector: "Humanoide Robotik / KI",
    ticker: "TSLA",
    priceTicker: "TSLA",
    wkn: "A1CX3T",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 160,
    buyZoneMax: 180,
    stopBuy: 230,
    stopLoss: 145,
    status: "Watchlist",
    notes: "Optimus / Robotik-Story",
  },
  {
    id: "rok",
    name: "Rockwell Automation",
    sector: "Industrieautomation",
    ticker: "ROK",
    priceTicker: "ROK",
    wkn: "903978",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 240,
    buyZoneMax: 260,
    stopBuy: 290,
    stopLoss: 225,
    status: "Watchlist",
    notes: "Industrie- und Fabrikautomatisierung",
  },
  {
    id: "cgnx",
    name: "Cognex",
    sector: "Machine Vision",
    ticker: "CGNX",
    priceTicker: "CGNX",
    wkn: "878090",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 32,
    buyZoneMax: 36,
    stopBuy: 42,
    stopLoss: 29,
    status: "Watchlist",
    notes: "Bildverarbeitung und Sensorik",
  },
  {
    id: "fanuy",
    name: "Fanuc",
    sector: "Industrierobotik",
    ticker: "FANUY",
    priceTicker: "FANUY",
    wkn: "863731",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 14,
    buyZoneMax: 16,
    stopBuy: 20,
    stopLoss: 13,
    status: "Watchlist",
    notes: "Robotik-Urgestein",
  },
  {
    id: "omrny",
    name: "OMRON",
    sector: "Sensorik / Automation",
    ticker: "OMRNY",
    priceTicker: "OMRNY",
    wkn: "856877",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 33,
    buyZoneMax: 37,
    stopBuy: 43,
    stopLoss: 30,
    status: "Watchlist",
    notes: "Sensorik und Fabrikautomation",
  },
  {
    id: "asml",
    name: "ASML",
    sector: "Chip-Infrastruktur",
    ticker: "ASML",
    priceTicker: "ASML",
    wkn: "A1J4U4",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 760,
    buyZoneMax: 820,
    stopBuy: 950,
    stopLoss: 720,
    status: "Watchlist",
    notes: "Nicht Robotik direkt, aber Basis der KI-Hardware",
  },
    {
    id: "nvda-wl",
    name: "Nvidia",
    sector: "KI / GPU Infrastruktur",
    ticker: "NVDA",
    priceTicker: "NVDA",
    wkn: "918422",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 160,
    buyZoneMax: 170,
    stopBuy: 195,
    stopLoss: 145,
    status: "Watchlist",
    notes: "KI-Infrastruktur / Robotik-Basis",
  },
  {
    id: "isrg-wl",
    name: "Intuitive Surgical",
    sector: "Medizinrobotik",
    ticker: "ISRG",
    priceTicker: "ISRG",
    wkn: "888024",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 450,
    buyZoneMax: 470,
    stopBuy: 515,
    stopLoss: 420,
    status: "Watchlist",
    notes: "OP-Robotik / Qualitätswert",
  },
  {
    id: "abb-wl",
    name: "ABB",
    sector: "Industrieautomation",
    ticker: "ABB",
    priceTicker: "ABBNY",
    wkn: "919730",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 75,
    buyZoneMax: 80,
    stopBuy: 92,
    stopLoss: 70,
    status: "Watchlist",
    notes: "Automation / Robotik-Fabriken",
  },
  {
    id: "sym-wl",
    name: "Symbotic",
    sector: "Logistikrobotik",
    ticker: "SYM",
    priceTicker: "SYM",
    wkn: "A3DK1X",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 42,
    buyZoneMax: 46,
    stopBuy: 55,
    stopLoss: 38,
    status: "Watchlist",
    notes: "Warehouse Automation",
  },
  {
    id: "ter-wl",
    name: "Teradyne",
    sector: "Cobots / Testsysteme",
    ticker: "TER",
    priceTicker: "TER",
    wkn: "859892",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 260,
    buyZoneMax: 275,
    stopBuy: 315,
    stopLoss: 240,
    status: "Watchlist",
    notes: "Cobots / Hidden Champion",
  },
  {
    id: "path-wl",
    name: "UiPath",
    sector: "Software-Robotik / RPA",
    ticker: "PATH",
    priceTicker: "PATH",
    wkn: "A3CND6",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 9,
    buyZoneMax: 10.5,
    stopBuy: 13,
    stopLoss: 8,
    status: "Watchlist",
    notes: "RPA / Software-Automation",
  },
  {
    id: "serv",
    name: "Serve Robotics",
    sector: "Lieferroboter",
    ticker: "SERV",
    priceTicker: "SERV",
    wkn: "A3EW4Q",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 7,
    buyZoneMax: 9,
    stopBuy: 11,
    stopLoss: 6,
    status: "Watchlist",
    notes: "Moonshot / Delivery Robotics",
  },
  {
    id: "oust",
    name: "Ouster",
    sector: "Lidar / Robotik-Sensorik",
    ticker: "OUST",
    priceTicker: "OUST",
    wkn: "A3ECDT",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 18,
    buyZoneMax: 21,
    stopBuy: 25,
    stopLoss: 16,
    status: "Watchlist",
    notes: "Lidar / Sensorik",
  },
  {
    id: "kitt",
    name: "Nauticus Robotics",
    sector: "Unterwasserrobotik",
    ticker: "KITT",
    priceTicker: "KITT",
    wkn: "A41GJ4",
    type: "watchlist",
    shares: 0,
    buyPrice: 0,
    targetWeight: 0,
    buyZoneMin: 0.7,
    buyZoneMax: 0.95,
    stopBuy: 1.2,
    stopLoss: 0.6,
    status: "Watchlist",
    notes: "Moonshot / Spezialrobotik",
  },
];

export const DEPOT_STOCKS = STOCKS.filter((item) => item.type === "depot");
export const WATCHLIST_STOCKS = STOCKS.filter((item) => item.type === "watchlist");